import Head from "next/head";
import Image from "next/image";
import ElHereje from "../public/ElHereje.png";
import cuchillo from "../public/cuchillo.jpg";
import lasviudas from "../public/Lasviudas.jpg";
import NavBar from "../components/Carousel";
import mani from "../public/mani.jpg";
import Link from "next/link";
import hospital from "../public/hospital.jpg";
import juzgado from "../public/juzgado.jpg";

export default function Home5() {
    return (
        <div>
            <Head>
                <title>Directorio de artículos</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-white">
                <section className="max-h-s bg-zinc-900">
                    <nav className="py-10 mb-12 flex justify-between text-white px-6">
                        <h1 className="text-6xl font-serif dark:text-white">
                            <Link href="/"> El Hereje</Link>
                        </h1>
                        <ul className="flex items-center px-4 text-3xl">
                            <li className="px-4">
                                <Link
                                    href="/articledir"
                                    className="group transition duration-300 font-serif"
                                >
                                    Directorio de artículos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <Link
                                    href="/games"
                                    className="group transition duration-300 font-serif"
                                >
                                    Pasatiempos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <button className="bg-white text-black px-4 py-2 rounded-full font-serif">
                                    Suscríbete
                                </button>
                            </li>
                        </ul>
                    </nav>
                </section>
            </main>
            <div>
                <h1 className="flex justify-center text-3xl p-4 font-serif">
                UN NIÑO MOVILIZA A LAS AUTORIDADES PARA LLAMAR LA ATENCIÓN DE SUS PADRES 
                </h1>
                <div class="flex justify-center items-center">
                    <Image src={hospital} alt="" />
                </div>
                <h2 className="px-5 font-serif mx-20">Ángel Simón Santos </h2>
                <h3 className="p-5 font-serif mx-20">19 de febrero de 2023 </h3>
                <div className="text-justify mx-40 py-10">
                    <p className="px-5 font-serif">
                    El pasado martes los servicios de emergencias recibían varias llamadas de un niño desde la misma casa, en la primera llamada un niño pedía auxilio diciendo que se encontraba atrapado debajo de una estantería en su casa, pero antes de decir la dirección de su casa la llamada se cortó, por lo que esperaron otra llamada del niño para saber si se encontraba en buen estado.
                    </p>
                    <p className="px-5 font-serif py-10">
                    A la hora las autoridades recibieron otra llamada del niño. En esta Quico afirmaba haberse tragado un clavo que se había encontrado en el suelo de su garaje por la mañana. Esta vez sí que obtuvieron la dirección, por lo que rápidamente una ambulancia y un coche de policía acudieron a su casa. El niño estaba solo en casa así que se le llevaron al hospital y se contactó con sus padres, que llegaron rápidamente. 
                    </p>
                    <div class="flex justify-center items-center">
                    <Image 
                    class="w-3/6"
                    src={juzgado}
                     alt="" />
                </div>
                    <p className="px-5 font-serif Link py-10">
                    Después de varias pruebas los médicos del hospital Clínico de Valladolid afirmaron que no se había tragado ningún clavo, por lo que el niño tuvo que confesar, y es que no se había tragado ningún clavo, solo padecía el llamado síndrome del príncipe destronado, debido al nacimiento de su hermana menor. {" "}
                        
                    </p>
                    <p className="px-5 font-serif">
                    Los padres han pedido disculpas y se tendrán que enfrentar a una cuantiosa multa impuesta por la jurisdicción judicial de Valladolid, para paliar los gastos de todo el personal movilizado por la historia de Quico. {" "}
                    </p>
                   
                    
                </div>
              
                
            </div>
            <footer class="p-4 bg-white  shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-zinc-900">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="#" class="hover:underline">El Hereje™</a>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6 ">Quiénes somos</Link>
        </li>
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6">Política de privacidad</Link>
        </li>
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6">Aviso legal</Link>
        </li>
        <li>
            <Link href="#" class="hover:underline">Contacto</Link>
        </li>
    </ul>
</footer>
        </div>
    );
}