import Head from "next/head";
import Image from "next/image";
import ElHereje from "../public/ElHereje.png";
import cuchillo from "../public/cuchillo.jpg";
import lasviudas from "../public/Lasviudas.jpg";
import NavBar from "./components/Carousel";
import mani from "../public/mani.jpg";
import Link from "next/link";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Directorio de artículos</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-white">
                <section className="max-h-s bg-zinc-900">
                    <nav className="py-10 mb-12 flex justify-between text-white px-6">
                        <h1 className="text-6xl font-serif dark:text-white">
                            <Link href="/"> El Hereje</Link>
                        </h1>
                        <ul className="flex items-center px-4 text-3xl">
                            <li className="px-4">
                                <Link
                                    href="/articledir"
                                    className="group transition duration-300 font-serif"
                                >
                                    Directorio de artículos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <Link
                                    href="/games"
                                    className="group transition duration-300 font-serif"
                                >
                                    Pasatiempos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <button className="bg-white text-black px-4 py-2 rounded-full font-serif">
                                    Suscríbete
                                </button>
                            </li>
                        </ul>
                    </nav>
                </section>
            </main>
            <div>
                <h1 className="flex justify-center text-3xl p-4 font-serif">
                    MUJER MATA A SU MARIDO EN SAN VALENTÍN Y PASA LA NOCHE
                    ENCERRADA CON EL
                </h1>
                <div class="flex justify-center items-center">
                    <Image src={lasviudas} alt="" />
                </div>
                <h2 className="px-5 font-serif mx-20">Ángel Simón Santos </h2>
                <h3 className="p-5 font-serif mx-20">17 de febrero de 2023 </h3>
                <div className="text-justify mx-40 py-10">
                    <p className="px-5 font-serif">
                        El pasado San Valentín la policía logro detener en Las
                        Viudas a la mujer que mató a su marido sobre las 20:00 y
                        se quedó encerrada con él durante 5 horas, ahora la
                        mujer ya está a disposición de la justicia y hemos
                        podido saber por parte de su abogado José Alfredo
                        Rodríguez porque cometió tal asesinato.
                    </p>
                    <p className="px-5 font-serif py-10">
                        Según el testimonio dado por la acusada hacia las 19:20
                        del 14 de febrero el hombre entro en casa en estado de
                        embriaguez. Carmen (la acusada) empezó una discusión
                        debido al estado en el que se encontraba su marido a tan
                        pronta hora el día de San Valentín, la acalorada
                        conversación desemboco rápidamente en la violencia
                        física por parte del marido, la cual según Carmen ya se
                        había propiciado en más de una ocasión.{" "}
                    </p>
                    <div class="flex justify-center items-center">
                    <Image 
                    class="w-3/6"
                    src={mani}
                     alt="" />
                </div>
                    <p className="px-5  Link py-10">
                        Debido al peligro que corría su vida Carmen alcanzo
                        rápidamente una escopeta que estaba a nombre de su
                        marido, pegándole así tres tiros en el pecho. Después de
                        dispararle le sentó en el sofá para hablar
                        tranquilamente con su marido mientras se encontraba en
                        estado de agonía, él moriría treinta minutos más tarde
                        de ocurrirse el suceso. Que su marido estuviese muerto
                        no le importuno, ya que siguió hablando con él durante 5
                        horas.{" "}
                        
                    </p>
                    <p className="px-5 font-serif">
                        Según el abogado de la acusada esto se produjo debido al
                        maltrato que había sufrido la victima durante el tiempo
                        de su matrimonio, por lo que no se debería de tener en
                        cuenta. Estas declaraciones han provocado un
                        levantamiento de varios grupos en Valladolid, los cuales
                        piden la puesta en libertad de la acusada. Las
                        manifestaciones han acabado con cinco heridos, dos de
                        ellos graves ingresados en el hospital Río Ortega.{" "}
                    </p>
                   
                    
                </div>
              
                
            </div>
            <footer class="p-4 bg-white  shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-zinc-900">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="#" class="hover:underline">El Hereje™</a>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6 ">Quiénes somos</Link>
        </li>
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6">Política de privacidad</Link>
        </li>
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6">Aviso legal</Link>
        </li>
        <li>
            <Link href="#" class="hover:underline">Contacto</Link>
        </li>
    </ul>
</footer>
        </div>
    );
}
