import Head from "next/head";
import Image from "next/image";
import ElHereje from "../public/ElHereje.png";
import cuchillo from "../public/cuchillo.jpg"
import NavBar from "./components/Carousel";
import lasviudas from "../public/Lasviudas.jpg";
import lola from "../public/lola.jpg";
import fosas from "../public/fosas.jpg";
import Link from "next/link";
import cinco from "../public/cinco.jpg";




export default function Home() {
    return (
        <div>
            <Head>
                <title>Directorio de artículos</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-white">
                <section className="max-h-s bg-zinc-900">
                    <nav className="py-10 mb-12 flex justify-between text-white px-6">
                        <h1 className="text-6xl font-jetbrains font-serif dark:text-white">
                            <Link href="/"> El Hereje</Link>
                        </h1>
                        <ul className="flex items-center font-serif px-4 text-3xl">
                            <li className="px-4">
                                <Link
                                    href="#"
                                    className="group transition font-serif duration-300"
                                >
                                    Directorio de artículos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"> </span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <Link
                                    href="/games"
                                    className="group transition duration-300"
                                >
                                    Pasatiempos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <button className="bg-white text-black px-4 py-2 rounded-full">
                                    Suscribete
                                </button>
                            </li>
                        </ul>
                    </nav>
                </section>
                <section className="max-h-s">
                    <div className="flex justify-center">
                        <h1 className="text-3xl p-4">
                            DIRECTORIO DE ARTÍCULOS
                        </h1>
                    </div>
                    <div className="flex justify-center">
                        <div className="columns-2">
                            <div className="w-full">
                                <Link
                                    href="/article1"
                                    class="flex float-left items-center bg-white border m-10 border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-zinc-900 dark:hover:bg-gray-700"
                                >
                                    <Image
                                        class="object-cover h-screen rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
                                        src={lasviudas}
                                        alt=""
                                    />
                                    <div class="flex flex-col justify-between p-4 leading-normal">
                                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                            MUJER MATA A SU MARIDO Y SE QUEDA HABLANDO CON EL
                                        </h5>
                                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                                        Este San Valentín una mujer ha matado a su marido y ha estado 5 horas hablando en el cadáver
                                        
                                        </p>
                                    </div>
                                </Link>
                            </div>

                            <div className="w-full">
                                <Link
                                    href="#"
                                    class="flex float-left items-center bg-white border m-10 border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-zinc-900 dark:hover:bg-gray-700"
                                >
                                    <Image
                                        class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
                                        src={fosas}
                                        alt=""
                                    />
                                    <div class="flex flex-col justify-between p-4 leading-normal">
                                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                        DESCUBIERTAS FOSAS COMUNES 
                                        </h5>
                                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                                        El pasado lunes se han encontrado lo que parecen ser fosas comunes en la localidad vallisoletana Villabañez
                                        </p>
                                    </div>
                                </Link>
                            </div>
                            <div className="w-full">
                                <a
                                    href="#"
                                    class="flex float-left items-center bg-white border m-10 border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-zinc-900 dark:hover:bg-gray-700"
                                >
                                    <Image
                                        class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
                                        src={cinco}
                                        alt=""
                                    />
                                    <div class="flex flex-col justify-between p-4 leading-normal">
                                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                        CRÍTICA DE “CINCO HORAS CON MARIO”
                                        </h5>
                                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                                        Nuestro famoso crítico Abel Villorejo ha hecho una crítica sobre la obra de teatro &quot Cinco horas con &quot
                                        </p>
                                    </div>
                                </a>
                            </div>
                            <div className="w-full">
                                <Link
                                    href="#"
                                    class="flex float-left items-center bg-white border m-10 border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-zinc-900 dark:hover:bg-gray-700"
                                >
                                    <Image
                                        class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
                                        src={ElHereje}
                                        alt=""
                                    />
                                    <div class="flex flex-col justify-between p-4 leading-normal">
                                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                        GONZALO BUTANERO GITANO
                                        </h5>
                                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                                        GONZALO BUTANERO GITANO GONZALO BUTANERO GITANO GONZALO BUTANERO GITANO GONZALO BUTANERO GITANO
                                        </p>
                                    </div>
                                </Link>
                            </div>
                            <div className="w-full">
                                <a
                                    href="#"
                                    class="flex float-left items-center bg-white border m-10 border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-zinc-900 dark:hover:bg-gray-700"
                                >
                                    <Image
                                        class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
                                        src={ElHereje}
                                        alt=""
                                    />
                                    <div class="flex flex-col justify-between p-4 leading-normal">
                                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                        GONZALO BUTANERO GITANO
                                        </h5>
                                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                                        GONZALO BUTANERO GITANO GONZALO BUTANERO GITANO GONZALO BUTANERO GITANO GONZALO BUTANERO GITANO
                                        </p>
                                    </div>
                                </a>
                            </div>
                            <div className="w-full">
                                <Link
                                    href="#"
                                    class="flex float-left items-center bg-white border m-10 border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-zinc-900 dark:hover:bg-gray-700"
                                >
                                    <Image
                                        class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
                                        src={cuchillo}
                                        alt=""
                                    />
                                    <div class="flex flex-col justify-between p-4 leading-normal">
                                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                            GONZALO BUTANERO GITANO
                                        </h5>
                                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                                        GONZALO BUTANERO GITANO GONZALO BUTANERO GITANO GONZALO BUTANERO GITANO GONZALO BUTANERO GITANO
                                        </p>
                                    </div>
                                </Link>
                                


                            </div>
                        </div>
                    </div>
                </section>
            </main>
            <footer class="p-4 bg-white  shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-zinc-900">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="https://flowbite.com/" class="hover:underline">El Hereje™</a>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6 ">Quiénes somos</Link>
        </li>
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6">Política de privacidad</Link>
        </li>
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6">Aviso legal</Link>
        </li>
        <li>
            <Link href="#" class="hover:underline">Contacto</Link>
        </li>
    </ul>
</footer>
        </div>

    );
}
