import Head from "next/head";
import Image from "next/image";
import ElHereje from "../public/ElHereje.png";
import cuchillo from "../public/cuchillo.jpg";
import lasviudas from "../public/Lasviudas.jpg";
import NavBar from "../components/Carousel";
import mani from "../public/fosas.jpg";
import villa from "../public/villa.jpg";
import Link from "next/link";

export default function Home2() {
    return (
        <div>
            <Head>
                <title>Directorio de artículos</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-white">
                <section className="max-h-s bg-zinc-900">
                    <nav className="py-10 mb-12 flex justify-between text-white px-6">
                        <h1 className="text-6xl font-serif dark:text-white">
                            <Link href="/"> El Hereje</Link>
                        </h1>
                        <ul className="flex items-center px-4 text-3xl">
                            <li className="px-4">
                                <Link
                                    href="/articledir"
                                    className="group transition duration-300 font-serif"
                                >
                                    Directorio de artículos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <Link
                                    href="/games"
                                    className="group transition duration-300 font-serif"
                                >
                                    Pasatiempos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <button className="bg-white text-black px-4 py-2 rounded-full font-serif">
                                    Suscríbete
                                </button>
                            </li>
                        </ul>
                    </nav>
                </section>
            </main>
            <div>
                <h1 className="flex justify-center text-3xl p-4 font-serif">
                    DESCUBIERTAS FOSAS COMUNES
                </h1>
                <div class="flex justify-center items-center">
                    <Image
                    class="w-3/6" 
                    src={villa}
                    alt="" 
                    />
                </div>
                <h2 className="px-5 font-serif mx-20">Niek Diez Ten Voorde</h2>
                <h3 className="p-5 font-serif mx-20">17 de febrero de 2023 </h3>
                <div className="text-justify mx-40 py-10">
                    <p className="px-5 font-serif">
                    El pasado lunes se encontraron lo que parecen ser los restos de una fosa común en la localidad de Villabañez. Los restos fueron analizados por los forenses y las pruebas de carbono indicaron que en efecto datan de la guerra civil española, ya que tienen aproximadamente 84 años de antigüedad. 
                    </p>
                    <p className="px-5 font-serif py-10">
                    Según los investigadores implicados se intentarán realizar pruebas de ADN para identificar la identidad de estos esqueletos. "Aún no estamos seguros de cuánta gente hay en esta fosa ni si hay alguna otra por la zona, pero tenemos claro que tendrán un final más digno que este" Nos declara Roberto, que dirige este proyecto. 
                    </p>
                    <div class="flex justify-center items-center">
                    <Image 
                    class="w-3/6"
                    src={mani}
                     alt="" />
                </div>
                    <p className="px-5 font-serif Link py-10">
                    La fosa se descubrió gracias a una vecina que paseaba por la zona y vio lo que parecía ser una calavera, pocas horas después las autoridades precintaban la zona para proceder a la investigación. 
                        
                    </p>
                    
                    
                </div>
              
                
            </div>
            <footer class="p-4 bg-white  shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-zinc-900">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="#" class="hover:underline">El Hereje™</a>. All Rights Reserved.
    </span>
    <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6 ">Quiénes somos</Link>
        </li>
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6">Política de privacidad</Link>
        </li>
        <li>
            <Link href="#" class="mr-4 hover:underline md:mr-6">Aviso legal</Link>
        </li>
        <li>
            <Link href="#" class="hover:underline">Contacto</Link>
        </li>
    </ul>
</footer>
        </div>
    );
}