import Head from "next/head";
import Image from "next/image";
import ElHereje from "../public/ElHereje.png";
import cuchillo from "../public/cuchillo.jpg";
import sopa from "../public/sopa.jpeg";
import pensando from "../public/pensando.jpg";
import NavBar from "../components/Carousel";
import Link from "next/link";

export default function Home() {
    return (
        <div className=" flex flex-col h-screen justify-between">
            <Head>
                <title>Pasatiempos</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-white">
                <section className=" bg-zinc-900">
                    <nav className="py-10 mb-12 flex justify-between text-white px-6">
                        <h1 className="text-6xl font-serif dark:text-white">
                            <Link href="/"> El Hereje</Link>
                        </h1>
                        <ul className="flex items-center px-4 text-3xl">
                            <li className="px-4">
                                <Link
                                    href="/articledir"
                                    className="group transition font-serif duration-300"
                                >
                                    Directorio de artículos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <Link
                                    href="games.js"
                                    className="group transition font-serif duration-300"
                                >
                                    Pasatiempos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <button className="bg-white text-black font-serif px-4 py-2 rounded-full">
                                    Suscribete
                                </button>
                            </li>
                        </ul>
                    </nav>
                </section>
                <section className="max-h-s">
                    <div className="flex justify-center font-serif">
                        <h1 className="text-3xl p-4">PASATIEMPOS</h1>
                    </div>
                    <div className="flex justify-center">
                        <div className="columns-2">
                            <div className="w-full">
                                <Link
                                    href="https://drive.google.com/file/d/1Frr0ZrFYWSm_mw1knfUPxY14GoffXD8K/view?usp=sharing"
                                    class="flex float-left items-center bg-white border m-10 border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700"
                                >
                                    <Image
                                        class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
                                        src={pensando}
                                        alt=""
                                    />
                                    <div class="flex flex-col justify-between p-4 leading-normal">
                                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                            COMPLETA NUESTRA NUEVA SOPA DE LETRAS
                                        </h5>
                                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                                            Consigue completar nuestra nueva sopa de letras inspirada en el libro de Miguel Delibes hecha por Angélica Gomez Carreño. Y recuerda la semana que viene publicamos las soluciones.
                                        
                                        </p>
                                    </div>
                                </Link>
                            </div>

                            <div className="w-full">
                                <Link
                                    href="https://drive.google.com/file/d/10qlN0csos8wGnYudI-DYp216airE2BqF/view?usp=sharing"
                                    class="flex float-left items-center bg-white border m-10 border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700"
                                >
                                    <Image
                                        class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg"
                                        src={pensando}
                                        alt=""
                                    />
                                    <div class="flex flex-col justify-between p-4 leading-normal">
                                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                            COMPLETA NUESTRO NUEVO CRUCIGRAMA
                                        </h5>
                                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                                        Consigue completar nuestro nuevo sopa crucigrama inspirado en el libro de Miguel Delibes hecha por Angélica Gomez Carreño. Y recuerda la semana que viene publicamos las soluciones.

                                        </p>
                                    </div>
                                </Link>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
            <footer class="p-4 bg-white shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-zinc-900">
                <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
                    © 2023{" "}
                    <Link href="https://flowbite.com/" class="hover:underline">
                        El Hereje™
                    </Link>
                    . All Rights Reserved.
                </span>
                <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
                    <li>
                        <Link href="#" class="mr-4 hover:underline md:mr-6 ">
                            Quiénes somos
                        </Link>
                    </li>
                    <li>
                        <Link href="#" class="mr-4 hover:underline md:mr-6">
                            Política de privacidad
                        </Link>
                    </li>
                    <li>
                        <Link href="#" class="mr-4 hover:underline md:mr-6">
                            Aviso legal
                        </Link>
                    </li>
                    <li>
                        <Link href="#" class="hover:underline">
                            Contacto
                        </Link>
                    </li>
                </ul>
            </footer>
        </div>
    );
}
