import Head from "next/head";
import Image from "next/image";
import deved from "../public/ElHereje.png";
import NavBar from "../components/Carousel";
import { Carousel } from "../components/Carousel";
import Link from "next/link";

export default function Home() {
    return (
        <div>
            <Head>
                <title>El hereje</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-white dark:bg-zinc-900 px-10">
                <section className="min-h-screen">
                    <nav className="py-10 mb-12 flex justify-between text-white">
                        <h1 className="text-6xl font-serif dark:text-white">
                            El Hereje
                        </h1>
                        <ul className="flex items-center px-4 text-3xl">
                            <li className="px-4">
                                <Link
                                    href="/articledir"
                                    className="group font-serif transition duration-300"
                                >
                                    Directorio de artículos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <Link
                                    href="/games"
                                    className="group transition font-serif duration-300"
                                >
                                    Pasatiempos
                                    <span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
                                </Link>
                            </li>
                            <li className="px-4">
                                <button className="bg-white text-black font-serif px-4 py-2 rounded-full">
                                    Suscribete
                                </button>
                            </li>
                        </ul>
                    </nav>
                    <div className="text-center p-10 py-5">
                        <div className="mx-auto border-4 border-white rounded-full w-80 h-80 relative overflow-hidden md:h-96 md:w-96">
                            <Image
                                src={deved}
                            />
                        </div>
                        <h2 className="text-5xl py-2 text-white font-medium md:text-6xl mt-12">
                            
                        </h2>
                        <Carousel />
                    </div>

                </section>
            </main>
            <footer class="p-4 bg-white shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-zinc-900">
                <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
                    © 2023{" "}
                    <Link href="https://flowbite.com/" class="hover:underline">
                        El Hereje™
                    </Link>
                    . All Rights Reserved.
                </span>
                <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
                    <li>
                        <Link href="#" class="mr-4 hover:underline md:mr-6 ">
                            Quiénes somos
                        </Link>
                    </li>
                    <li>
                        <Link href="#" class="mr-4 hover:underline md:mr-6">
                            Política de privacidad
                        </Link>
                    </li>
                    <li>
                        <Link href="#" class="mr-4 hover:underline md:mr-6">
                            Aviso legal
                        </Link>
                    </li>
                    <li>
                        <Link href="#" class="hover:underline">
                            Contacto
                        </Link>
                    </li>
                </ul>
            </footer>
        </div>
    );
}
